require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rake
  - rubocop-factory_bot
AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 100
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false